import { readRuntimeLanguage } from './runtimeLanguage';

const norwegianTeamNames: Record<string, string> = {
	MEX: 'Mexico',
	RSA: 'Sør-Afrika',
	KOR: 'Sør-Korea',
	CZE: 'Tsjekkia',
	CAN: 'Canada',
	BIH: 'Bosnia-Hercegovina',
	QAT: 'Qatar',
	SUI: 'Sveits',
	BRA: 'Brasil',
	MAR: 'Marokko',
	HAI: 'Haiti',
	SCO: 'Skottland',
	USA: 'USA',
	PAR: 'Paraguay',
	AUS: 'Australia',
	TUR: 'Tyrkia',
	GER: 'Tyskland',
	CUW: 'Curaçao',
	CIV: 'Elfenbenskysten',
	ECU: 'Ecuador',
	NED: 'Nederland',
	JPN: 'Japan',
	SWE: 'Sverige',
	TUN: 'Tunisia',
	BEL: 'Belgia',
	EGY: 'Egypt',
	IRN: 'Iran',
	NZL: 'New Zealand',
	ESP: 'Spania',
	CPV: 'Kapp Verde',
	KSA: 'Saudi-Arabia',
	URU: 'Uruguay',
	FRA: 'Frankrike',
	SEN: 'Senegal',
	IRQ: 'Irak',
	NOR: 'Norge',
	ARG: 'Argentina',
	ALG: 'Algerie',
	AUT: 'Østerrike',
	JOR: 'Jordan',
	POR: 'Portugal',
	COD: 'DR Kongo',
	UZB: 'Usbekistan',
	COL: 'Colombia',
	ENG: 'England',
	CRO: 'Kroatia',
	GHA: 'Ghana',
	PAN: 'Panama'
};

const englishTeamNames: Record<string, string> = {
	MEX: 'Mexico',
	RSA: 'South Africa',
	KOR: 'South Korea',
	CZE: 'Czech Republic',
	CAN: 'Canada',
	BIH: 'Bosnia and Herzegovina',
	QAT: 'Qatar',
	SUI: 'Switzerland',
	BRA: 'Brazil',
	MAR: 'Morocco',
	HAI: 'Haiti',
	SCO: 'Scotland',
	USA: 'USA',
	PAR: 'Paraguay',
	AUS: 'Australia',
	TUR: 'Turkey',
	GER: 'Germany',
	CUW: 'Curaçao',
	CIV: 'Ivory Coast',
	ECU: 'Ecuador',
	NED: 'Netherlands',
	JPN: 'Japan',
	SWE: 'Sweden',
	TUN: 'Tunisia',
	BEL: 'Belgium',
	EGY: 'Egypt',
	IRN: 'Iran',
	NZL: 'New Zealand',
	ESP: 'Spain',
	CPV: 'Cape Verde',
	KSA: 'Saudi Arabia',
	URU: 'Uruguay',
	FRA: 'France',
	SEN: 'Senegal',
	IRQ: 'Iraq',
	NOR: 'Norway',
	ARG: 'Argentina',
	ALG: 'Algeria',
	AUT: 'Austria',
	JOR: 'Jordan',
	POR: 'Portugal',
	COD: 'DR Congo',
	UZB: 'Uzbekistan',
	COL: 'Colombia',
	ENG: 'England',
	CRO: 'Croatia',
	GHA: 'Ghana',
	PAN: 'Panama'
};

const chineseTeamNames: Record<string, string> = {
	MEX: '墨西哥',
	RSA: '南非',
	KOR: '韩国',
	CZE: '捷克',
	CAN: '加拿大',
	BIH: '波黑',
	QAT: '卡塔尔',
	SUI: '瑞士',
	BRA: '巴西',
	MAR: '摩洛哥',
	HAI: '海地',
	SCO: '苏格兰',
	USA: '美国',
	PAR: '巴拉圭',
	AUS: '澳大利亚',
	TUR: '土耳其',
	GER: '德国',
	CUW: '库拉索',
	CIV: '科特迪瓦',
	ECU: '厄瓜多尔',
	NED: '荷兰',
	JPN: '日本',
	SWE: '瑞典',
	TUN: '突尼斯',
	BEL: '比利时',
	EGY: '埃及',
	IRN: '伊朗',
	NZL: '新西兰',
	ESP: '西班牙',
	CPV: '佛得角',
	KSA: '沙特阿拉伯',
	URU: '乌拉圭',
	FRA: '法国',
	SEN: '塞内加尔',
	IRQ: '伊拉克',
	NOR: '挪威',
	ARG: '阿根廷',
	ALG: '阿尔及利亚',
	AUT: '奥地利',
	JOR: '约旦',
	POR: '葡萄牙',
	COD: '刚果（金）',
	UZB: '乌兹别克斯坦',
	COL: '哥伦比亚',
	ENG: '英格兰',
	CRO: '克罗地亚',
	GHA: '加纳',
	PAN: '巴拿马'
};

const chineseNameAliases: Record<string, string> = {
	Mexico: '墨西哥',
	'México': '墨西哥',
	'South Africa': '南非',
	'Sør-Afrika': '南非',
	'South Korea': '韩国',
	'Sør-Korea': '韩国',
	'Czech Republic': '捷克',
	Tsjekkia: '捷克',
	Canada: '加拿大',
	'Bosnia and Herzegovina': '波黑',
	'Bosnia-Hercegovina': '波黑',
	Qatar: '卡塔尔',
	Switzerland: '瑞士',
	Sveits: '瑞士',
	Brazil: '巴西',
	Brasil: '巴西',
	Morocco: '摩洛哥',
	Marokko: '摩洛哥',
	Haiti: '海地',
	Scotland: '苏格兰',
	Skottland: '苏格兰',
	USA: '美国',
	Paraguay: '巴拉圭',
	Australia: '澳大利亚',
	Turkey: '土耳其',
	Tyrkia: '土耳其',
	Germany: '德国',
	Deutschland: '德国',
	Tyskland: '德国',
	'Curaçao': '库拉索',
	'Ivory Coast': '科特迪瓦',
	Elfenbenskysten: '科特迪瓦',
	Ecuador: '厄瓜多尔',
	Netherlands: '荷兰',
	Nederland: '荷兰',
	Japan: '日本',
	Sweden: '瑞典',
	Sverige: '瑞典',
	Tunisia: '突尼斯',
	Belgium: '比利时',
	Belgia: '比利时',
	Egypt: '埃及',
	Iran: '伊朗',
	'New Zealand': '新西兰',
	Spain: '西班牙',
	Spania: '西班牙',
	'Cape Verde': '佛得角',
	'Kapp Verde': '佛得角',
	'Saudi Arabia': '沙特阿拉伯',
	'Saudi-Arabia': '沙特阿拉伯',
	Uruguay: '乌拉圭',
	France: '法国',
	Frankrike: '法国',
	Senegal: '塞内加尔',
	Iraq: '伊拉克',
	Irak: '伊拉克',
	Norway: '挪威',
	Norge: '挪威',
	Noreg: '挪威',
	Argentina: '阿根廷',
	Algeria: '阿尔及利亚',
	Algerie: '阿尔及利亚',
	Austria: '奥地利',
	'Østerrike': '奥地利',
	Jordan: '约旦',
	Portugal: '葡萄牙',
	'DR Congo': '刚果（金）',
	'DR Kongo': '刚果（金）',
	Uzbekistan: '乌兹别克斯坦',
	Usbekistan: '乌兹别克斯坦',
	Colombia: '哥伦比亚',
	England: '英格兰',
	Croatia: '克罗地亚',
	Kroatia: '克罗地亚',
	Ghana: '加纳',
	Panama: '巴拿马'
};

export function teamDisplayName(
	team: { name?: string; fifaCode?: string } | null | undefined,
	fallback = ''
) {
	if (!team) return fallback;
	const lang = readRuntimeLanguage();
	const names = lang === 'zh-CN' ? chineseTeamNames : lang === 'en' ? englishTeamNames : norwegianTeamNames;
	const raw = team.name || fallback;
	return (team.fifaCode && names[team.fifaCode]) || (lang === 'zh-CN' && raw ? chineseNameAliases[raw] : '') || raw;
}
