const zh: Record<string, string> = {
	'4 errors': '4 个错误',
	'on the last match': '在最后一场比赛',
	'1/X/2 in group stage, the team that advances in knockout': '小组赛猜 1/X/2，淘汰赛猜晋级球队',
	'1/X/2 in group stage; in knockout, picking the advancing team counts as the correct outcome': '小组赛猜 1/X/2；淘汰赛猜中晋级球队即为赛果方向正确',
	'1st': '第 1',
	'2nd': '第 2',
	'3rd': '第 3',
	'3rd place': '第 3 名',
	'About the game': '关于游戏',
	'Active streak': '当前连续得分',
	'Add an outsider if they are not in the shortlist.': '如果球员不在候选名单中，可以添加黑马球员。',
	'Add player': '添加球员',
	'Add to list': '加入名单',
	'Adding…': '添加中…',
	'Already have an account?': '已有账号？',
	'All': '全部',
	'All open matches that can be tipped right now are filled in.': '当前可预测的比赛都已填写。',
	'Back': '返回',
	'Back to sign in': '返回登录',
	'Best thirds': '最佳小组第三',
	'Betting odds': '赔率',
	'Biggest miss': '最大偏差',
	'Bracket': '赛程图',
	'Change photo': '更换头像',
	'Changes are saved automatically': '更改会自动保存',
	'Choose a new password': '设置新密码',
	'Choose an image file.': '请选择图片文件。',
	'Close': '关闭',
	'Close intro card': '关闭介绍卡片',
	'Close search': '关闭搜索',
	'Confirm new password': '确认新密码',
	'Continue with Google': '使用 Google 继续',
	'Could not add this player.': '无法添加该球员。',
	'Could not create account.': '无法创建账号。',
	'Could not delete account.': '无法删除账号。',
	'Could not save changes.': '无法保存更改。',
	'Could not search players.': '无法搜索球员。',
	'Could not send reset link.': '无法发送重置链接。',
	'Could not update password.': '无法更新密码。',
	'Create account': '创建账号',
	'Create account.': '创建账号。',
	'Current streak': '当前连续得分',
	'Dark theme': '深色主题',
	'Delete account': '删除账号',
	'Delete my account': '删除我的账号',
	'Deleting…': '删除中…',
	'Display name': '显示名称',
	'Draw': '平局',
	'Email': '邮箱',
	'English': 'English',
	'Enter and confirm your new password.': '请输入并确认你的新密码。',
	'Enter the email you signed up with and we will send a reset link.': '输入注册邮箱，我们会发送重置链接。',
	'Error': '错误',
	'FIFA ranking': 'FIFA 排名',
	'Failed': '失败',
	'Find a match, team or league.': '查找比赛、球队或联赛。',
	'Forgot password?': '忘记密码？',
	'Golden Boot': '金靴',
	'Golden Boot pick': '金靴预测',
	'Golden Boot pick and current top-scorer table.': '金靴预测和当前射手榜。',
	'Goals': '进球',
	'Got it': '知道了',
	'Group': '小组',
	'Group tables': '小组积分榜',
	'Groups': '小组',
	'Hide friends’ tips': '隐藏好友预测',
	'Hit rate': '命中率',
	'Home': '首页',
	'How everyone tipped': '大家的预测',
	'How points work': '计分规则',
	'If the email is registered, a link is on the way.': '如果该邮箱已注册，重置链接将发送到邮箱。',
	'Image must be 5 MB or smaller.': '图片大小不能超过 5 MB。',
	'Install': '安装',
	'Install VM Tipping': '安装 VM Tipping',
	'Join the World Cup tipping competition.': '加入世界杯预测比赛。',
	'Jump to current round': '跳到当前轮次',
	'Knockout': '淘汰赛',
	'Knockout bracket': '淘汰赛赛程图',
	'Lagret': '已保存',
	'Leagues': '联赛',
	'Light theme': '浅色主题',
	'Live': '直播中',
	'Live API search unavailable': '实时 API 搜索不可用',
	'Load failed': '加载失败',
	'Loading search…': '正在加载搜索…',
	'Loading matches…': '正在加载比赛…',
	'Loading…': '加载中…',
	'Lock': '锁定',
	'Locked.': '已锁定。',
	'Locks': '锁定时间',
	'Locks at kickoff.': '开球时锁定。',
	'Log in': '登录',
	'Log in and beat your': '登录并击败你的',
	'Log out': '退出登录',
	'Match tips': '比赛预测',
	'Match Tips': '比赛预测',
	'Matches': '比赛',
	'matches': '比赛',
	'Matches you haven’t tipped': '尚未预测的比赛',
	'Missing': '未填写',
	'New here?': '新用户？',
	'New password': '新密码',
	'No Golden Boot pick.': '暂无金靴预测。',
	'No best-third picks.': '暂无最佳小组第三预测。',
	'No candidates yet.': '暂无候选人。',
	'No goals registered yet.': '尚无进球记录。',
	'No leagues': '暂无联赛',
	'No local candidates matched, and live API search is unavailable.': '本地没有匹配候选人，实时 API 搜索不可用。',
	'No matching World Cup candidates found.': '没有找到匹配的世界杯候选人。',
	'No missing match tips': '没有遗漏的比赛预测',
	'No one else has picked this match.': '还没有其他人预测这场比赛。',
	'No one in this league has picked this match.': '这个联赛中还没有人预测这场比赛。',
	'No results.': '没有结果。',
	'No scored matches yet.': '暂无已计分比赛。',
	'Points update automatically as results come in.': '赛果录入后积分会自动更新。',
	'Not allowed': '无权访问',
	'Not synced yet': '尚未同步',
	'Notifications': '通知',
	'OR': '或',
	'Open leagues': '打开联赛',
	'Password': '密码',
	'Password must be at least 8 characters.': '密码至少需要 8 个字符。',
	'Password updated — sending you to sign in…': '密码已更新，即将跳转到登录页…',
	'Penalties': '点球',
	'Pick': '选择',
	'Picked': '已预测',
	'Player': '球员',
	'Player card': '玩家卡片',
	'PNG or JPG, up to 5 MB.': 'PNG 或 JPG，最大 5 MB。',
	'Pre-kickoff reminder': '开球前提醒',
	'Predicted champion': '预测冠军',
	'Predicted winner': '预测冠军',
	'Pts': '分',
	'Push': '推送',
	'Read-only - a friend\'s World Cup tips.': '只读 - 好友的世界杯预测。',
	'Reset link sent - check your inbox.': '重置链接已发送，请检查收件箱。',
	'Reset password': '重置密码',
	'Result': '赛果',
	'Round': '轮次',
	'Save': '保存',
	'Save changes': '保存更改',
	'Save failed': '保存失败',
	'Saved': '已保存',
	'Saved · changes are saved automatically': '已保存 · 更改会自动保存',
	'Saving…': '保存中…',
	'Scored tips': '已计分预测',
	'Search': '搜索',
	'Search by player name…': '按球员姓名搜索…',
	'Search for a Golden Boot player': '搜索金靴球员',
	'Search in VM Tipping': '搜索 VM Tipping',
	'Search match, team, group or league': '搜索比赛、球队、小组或联赛',
	'Search more players': '搜索更多球员',
	'Searching…': '搜索中…',
	'See match tips': '查看比赛预测',
	'Send link': '发送链接',
	'Send reset link': '发送重置链接',
	'Send test notification': '发送测试通知',
	'Sending…': '发送中…',
	'Sent': '已发送',
	'Settings': '设置',
	'Shortlist': '候选名单',
	'Show %': '显示 %',
	'Show friends’ tips': '显示好友预测',
	'Show odds': '显示赔率',
	'Show the welcome card again': '重新显示欢迎卡片',
	'Sign in': '登录',
	'Simplified Chinese': '简体中文',
	'Standard theme': '标准主题',
	'Submit before kickoff.': '开球前提交预测。',
	'Team': '球队',
	'Teams': '球队',
	'The card is active and will stay on the home page until you close it.': '欢迎卡片已启用，会显示在首页，直到你关闭它。',
	'The card is hidden for this user on this device.': '欢迎卡片已在此设备上对该用户隐藏。',
	'The link is invalid or expired.': '链接无效或已过期。',
	'The official Golden Boot standings.': '官方金靴榜。',
	'The passwords do not match.': '两次输入的密码不一致。',
	'The tournament has started - the World Cup tip is final.': '赛事已开始 - 世界杯预测已锁定。',
	'Today': '今天',
	'Top scorers': '射手榜',
	'Top-scorer pick': '金靴预测',
	'Tournament': '赛事',
	'Try another tab.': '试试其他标签。',
	'Type to search...': '输入关键词搜索…',
	'Update password': '更新密码',
	'Updated': '更新于',
	'View all matches': '查看全部比赛',
	'Welcome card': '欢迎卡片',
	'Welcome to VM Tipping': '欢迎使用 VM Tipping',
	'Where the tournament is now': '赛事当前进度',
	'Where we are now': '当前进度',
	'Whole tournament': '整届赛事',
	'World Cup Tips': '世界杯预测',
	'World Cup theme': '世界杯主题',
	'World Cup tips': '世界杯预测',
	'World Cup tip': '世界杯预测',
	'World Cup tips in one league.': '一个联赛里完成世界杯预测。',
	'Wrong email or password.': '邮箱或密码错误。',
	'You tipped': '你的预测',
	'Your Golden Boot pick': '你的金靴预测',
	'Your tip': '你的预测',
	'actual': '实际',
	'advances': '晋级',
	'aet': '加时后',
	'gap': '偏差',
	'helt rette': '完全命中',
	'locked': '已锁定',
	'missing': '未填写',
	'now': '现在',
	'on TV': '电视转播',
	'pens': '点球',
	'same score as the final result': '比分完全命中',
	'through': '晋级',
	'to simulate the tournament.': '来模拟赛事。',
	'top-scorer pick': '金靴预测',
	'vs': 'vs',
	'you': '你',
	'Good night': '晚上好',
	'Good morning': '早上好',
	'Good evening': '晚上好',
	'Hi': '你好',
	'Play against your friends': '和朋友一起比赛',
	'Pick a league, see the table, and jump straight to chat.': '选择联赛、查看积分榜，并直接进入聊天。',
	'Your leagues': '你的联赛',
	'Create league': '创建联赛',
	'Start a new private competition.': '发起新的私人比赛。',
	'League name': '联赛名称',
	'Create': '创建',
	'Join': '加入',
	'Paste the code from the invite.': '粘贴邀请中的代码。',
	'Pick the result for every match. You can change it until kickoff.': '预测每场比赛的赛果，开球前都可以修改。',
	'Want notifications?': '要开启提醒吗？',
	'We can remind you to submit your tips before matches start. Choose how.': '我们可以在比赛开始前提醒你提交预测。请选择提醒方式。',
	'Reminders by email.': '通过邮箱提醒。',
	'Notifications straight to your device.': '直接向你的设备发送通知。',
	'Not supported in this browser.': '此浏览器不支持。',
	'Not now': '暂不开启',
	'Turn on': '开启',
	'You can change this any time in Settings.': '你可以随时在设置中修改。',
	'New': '新',
	'new': '新',
	'Not tipped': '未预测',
	'Perfect! ': '完美！',
	'You got ': '你获得了 ',
	' on the last match': '（上一场比赛）',
	'Right now': '当前',
	'Checking your tips': '正在检查你的预测',
	'Fetching match status, points, and league.': '正在获取比赛状态、积分和联赛。',
	'Open match tips': '打开比赛预测',
	'Live now': '正在直播',
	'Follow the matches in real time': '实时关注比赛',
	'View match': '查看比赛',
	'View matches': '查看比赛',
	'Next action': '下一步',
	'This tip must be submitted before kickoff.': '这条预测必须在开球前提交。',
	'The remaining match tips must be submitted before kickoff.': '剩余比赛预测必须在开球前提交。',
	'Tip the match': '预测这场比赛',
	'Go to match tips': '前往比赛预测',
	'Deadline': '截止时间',
	'The World Cup tip must be submitted before kickoff': '世界杯预测必须在开赛前提交',
	'Set groups, best thirds, and knockout before the tournament starts.': '在赛事开始前设置小组排名、最佳第三名和淘汰赛。',
	'Open World Cup tips': '打开世界杯预测',
	'Tournament over': '赛事结束',
	'World Cup is over 🎊🏆': '世界杯结束了 🎊🏆',
	'Fantastic predictions! Your final standings are below.': '预测很精彩！你的最终排名见下方。',
	'Your final league standings are ready below.': '你的最终联赛排名见下方。',
	'Thanks for playing. Your final standings are ready below.': '感谢参与。你的最终排名见下方。',
	'View standings': '查看排名',
	'Latest result': '最新赛果',
	'View result': '查看赛果',
	'All set': '已就绪',
	'Ready': '就绪',
	'You are ready for the tournament.': '你已为赛事做好准备。',
	'Winner': '冠军',
	'Runner-up': '亚军',
	'Third place': '季军',
	'World Cup gold': '世界杯冠军',
	'World Cup silver': '世界杯亚军',
	'World Cup bronze': '世界杯季军',
	'Unknown': '未知',
	'Loading your World Cup tip': '正在加载你的世界杯预测',
	'We are checking groups, knockout, and podium.': '正在检查小组、淘汰赛和领奖台预测。',
	'Enter groups, best thirds, and knockout.': '填写小组、最佳第三名和淘汰赛。',
	'Submit World Cup tip': '提交世界杯预测',
	'The tournament is finished.': '赛事已结束。',
	'View World Cup tips': '查看世界杯预测',
	'Your World Cup tip is ready': '你的世界杯预测已就绪',
	'Your podium is locked in when the tournament starts.': '赛事开始后，你的前三名预测将锁定。',
	'Your guess is alive': '你的预测仍有机会',
	'Your winner is out': '你预测的冠军已出局',
	'In play': '进行中',
	'Follow groups and knockout as results come in.': '随着赛果更新，关注小组和淘汰赛。',
	'Tournament finished': '赛事已结束',
	'Your league standings will show here.': '你的联赛排名会显示在这里。',
	'HT': '半场',
	'ET': '加时',
	'Pens': '点球',
	'World Cup 2026 · 11 June - 19 July': '2026 世界杯 · 6月11日 - 7月19日',
	'League status missing': '缺少联赛状态',
	'Points': '积分',
	'Live events': '实时事件',
	'Assist': '助攻',
	'OG': '乌龙',
	'Points trend': '积分趋势',
	'Match points': '比赛积分',
	'last 3': '最近 3 场',
	'Avg': '平均',
	'Exact': '完全命中',
	'League table': '联赛积分榜',
	'Choose league for league table': '选择要查看积分榜的联赛',
	'Table': '积分榜',
	'You won the league': '你赢得了联赛',
	'You lead the league': '你领跑联赛',
	'You are on the table': '你已进入积分榜',
	'Chasing': '追赶中',
	'level': '同分',
	'Latest from league chat': '联赛聊天最新消息',
	'Could not fetch the latest chat right now.': '暂时无法获取最新聊天。',
	'Message deleted': '消息已删除',
	'No messages yet': '暂无消息',
	'Upcoming matches': '即将开始的比赛',
	'Submitted': '已提交',
	'Final standings': '最终排名',
	'Latest results': '最新赛果',
	'All leagues': '所有联赛',
	'Yours': '你的',
	'Top scorer and your player': '最佳射手与你的球员',
	'Top scorer table': '射手榜',
	'My player': '我的球员',
	'You picked the winner': '你选中了冠军',
	'No placing in the final table': '最终榜单无排名',
	'World champion': '世界冠军',
	'World Cup tips before kickoff': '开赛前提交世界杯预测',
	'Set the group order, best thirds, full knockout bracket, and one top-scorer pick before the first whistle. You can also search and add an outsider if the shortlist is too narrow.': '在第一声哨响前设置小组排名、最佳第三名、完整淘汰赛树和一个最佳射手预测。如果候选名单不够，也可以搜索并添加黑马球员。',
	'Match tips before every game': '每场比赛前提交比赛预测',
	'Pick the score for every match. You can change it right up until kickoff.': '预测每场比赛的比分，开球前都可以修改。',
	'The tip locks': '预测会锁定',
	'When the game starts, your tip locks and friends’ tips become visible in leagues.': '比赛开始后，你的预测会锁定，好友预测会在联赛中可见。',
	'Points along the way': '赛事期间持续计分',
	'Results, tables, and points update continuously through the group stage and knockout rounds.': '小组赛和淘汰赛期间，赛果、积分榜和分数会持续更新。',
	'Correct outcome': '赛果方向正确',
	'Correct winners': '正确胜者',
	'Correct winner': '正确胜者',
	'Correct winners (tiebreaker 2)': '正确胜者（同分规则 2）',
	'Exact scores': '精确比分',
	'Exact scores (tiebreaker 1)': '精确比分（同分规则 1）',
	'Goal-difference error': '净胜球误差',
	'Goal-difference error (tiebreaker 3, lower is better)': '净胜球误差（同分规则 3，越低越好）',
	'Matches tipped': '已预测比赛',
	'World Cup tip points': '世界杯预测积分',
	'Match tip points': '比赛预测积分',
	'Per match (match tips)': '每场比赛（比赛预测）',
	'Correct result - group stage: H / D / A; knockout: the team that advances': '赛果方向正确 - 小组赛：主胜 / 平 / 客胜；淘汰赛：晋级球队',
	'Correct total goals': '总进球数正确',
	'Correct goal difference': '净胜球正确',
	'Knockout matches cannot end in a draw - the result points go to the team that advances. If a knockout match is decided in extra time, the score after extra time is used for points.': '淘汰赛不会以平局结束——赛果方向分给猜中晋级球队的一方。如果淘汰赛在加时后决出胜负，则按加时后比分计分。',
	'Exact score': '比分完全命中',
	'Total goals': '总进球数',
	'for example 2-1 and 3-0 both count as 3 goals': '例如 2-1 和 3-0 都是 3 个总进球',
	'for example a one-goal win or a draw': '例如赢 1 球或平局',
	'Correct group placement': '小组名次正确',
	'Perfect group': '小组完全命中',
	'Correct team through': '晋级球队正确',
	'R32 / R16 / QF': '32 强 / 16 强 / 8 强',
	'SF / Final / Winner': '半决赛 / 决赛 / 冠军',
	'Correct Golden Boot winner': '金靴得主正确',
	'Create private leagues, share an invite, and follow the table together.': '创建私人联赛、分享邀请，并一起关注积分榜。',
	'See groups, fixtures, and the knockout tree as the World Cup unfolds.': '随着世界杯推进，查看小组、赛程和淘汰赛树。',
	'Overview': '概览',
	'The home page shows what is missing, the next deadline, and your standing.': '首页会显示遗漏项、下一截止时间和你的排名。',
	'Close and go back': '关闭并返回',
	'How VM Tipping works': 'VM Tipping 玩法说明',
	'Pick the full World Cup and one top scorer before kickoff, search and add another player if you back a breakout scorer, enter match tips before every game, and compete with friends in leagues as the tournament rolls on.': '开赛前预测完整世界杯和一名最佳射手；如果看好黑马射手，可搜索并添加其他球员；每场比赛前填写比赛预测，并在赛事期间与好友联赛竞争。',
	'Quick overview': '快速概览',
	'max per game': '每场最高分',
	'How it flows': '玩法流程',
	'The app and the game': '应用与玩法',
	'Scoring system': '计分系统',
	'Max 6 points per match. In knockout, the advancing team counts as the correct outcome.': '每场比赛最高 6 分。淘汰赛中，晋级球队算作赛果方向正确。',
	'The World Cup tip locks at the first match and scores as groups, rounds, champion, and Golden Boot are decided.': '世界杯预测会在首场比赛开始时锁定，并随着小组、轮次、冠军和金靴结果确定而计分。',
	'If points are tied, the table sorts by most exact scores, most correct winners, lowest goal-difference error, fewest submitted tips, and earliest submission.': '如果积分相同，按完全命中次数、正确胜者次数、最低净胜球误差、提交预测数更少和提交更早依次排序。',
	'Support and bug reports': '支持与问题反馈',
	'Need help or want to report a bug? Send an email to the address below.': '需要帮助或想反馈问题？请发送邮件到下方地址。',
	'Support': '支持',
	'coworker': '同事',
	'friend': '朋友',
	'Join friends for World Cup match tips, leagues, points and chat.': '和朋友一起玩世界杯比赛预测、联赛、积分和聊天。',
	'World Cup tips with friends': '和朋友一起预测世界杯',
	'Tip every match, build your World Cup bracket, and follow the league drama as the points land.': '预测每一场比赛，搭建你的世界杯赛程图，并在积分更新时追踪联赛战况。',
	'Sign in actions': '登录选项',
	'Opening Google...': '正在打开 Google…',
	'Log in with Google': '使用 Google 登录',
	'Use email': '使用邮箱',
	'App preview': '应用预览',
	'Next deadline': '下一截止时间',
	'Brazil': '巴西',
	'Norway': '挪威',
	'Germany': '德国',
	'Mexico': '墨西哥',
	'Japan': '日本',
	'outcome': '赛果',
	'exact': '比分',
	'goals': '进球',
	'diff': '净胜球',
	'Submit tip': '提交预测',
	'Inside the app': '应用内功能',
	'Everything feels like match day.': '一切都像比赛日一样紧张。',
	'Group table': '小组积分榜',
	'Points system': '计分系统',
	'Goal difference': '净胜球差',
	'max per match': '每场最高分',
	'League chat': '联赛聊天',
	'That 90th minute goal changed everything.': '第 90 分钟的进球改变了一切。',
	'I had 2-1. Six points!': '我猜的是 2-1，六分！',
	'Private leagues, live reactions': '私人联赛，实时互动',
	'Ready before kickoff': '开球前准备就绪',
	'Make the first pick now.': '现在提交第一个预测。',
	'Need support or want to report a bug? Email': '需要支持或想反馈问题？请发送邮件至'
};

export function translateChinese(text: string): string {
	return zh[text] ?? text;
}

export function translateChineseValue(value: unknown): unknown {
	if (typeof value === 'string') return translateChinese(value);
	if (Array.isArray(value)) return value.map((item) => translateChineseValue(item));
	if (value && typeof value === 'object') {
		return Object.fromEntries(
			Object.entries(value).map(([key, item]) => [key, translateChineseValue(item)])
		);
	}
	return value;
}
