const zh: Record<string, string> = {
	'4 errors': '4 个错误',
	'on the last match': '在最后一场比赛',
	'1/X/2 in group stage, the team that advances in knockout': '小组赛猜 1/X/2，淘汰赛猜晋级球队',
	'1st': '第 1',
	'2nd': '第 2',
	'3rd': '第 3',
	'3rd place': '第 3 名',
	'About the game': '关于游戏',
	'Active streak': '当前连续得分',
	'Add an outsider if they are not in the shortlist.': '如果球员不在候选名单中，可以添加黑马球员。',
	'Add player': '添加球员',
	'Add to list': '加入名单',
	'Adding…': '添加中…',
	'Already have an account?': '已有账号？',
	'All': '全部',
	'All open matches that can be tipped right now are filled in.': '当前可预测的比赛都已填写。',
	'Back': '返回',
	'Back to sign in': '返回登录',
	'Best thirds': '最佳小组第三',
	'Betting odds': '赔率',
	'Biggest miss': '最大偏差',
	'Bracket': '赛程图',
	'Change photo': '更换头像',
	'Changes are saved automatically': '更改会自动保存',
	'Choose a new password': '设置新密码',
	'Choose an image file.': '请选择图片文件。',
	'Close': '关闭',
	'Close intro card': '关闭介绍卡片',
	'Close search': '关闭搜索',
	'Confirm new password': '确认新密码',
	'Continue with Google': '使用 Google 继续',
	'Could not add this player.': '无法添加该球员。',
	'Could not create account.': '无法创建账号。',
	'Could not delete account.': '无法删除账号。',
	'Could not save changes.': '无法保存更改。',
	'Could not search players.': '无法搜索球员。',
	'Could not send reset link.': '无法发送重置链接。',
	'Could not update password.': '无法更新密码。',
	'Create account': '创建账号',
	'Create account.': '创建账号。',
	'Current streak': '当前连续得分',
	'Dark theme': '深色主题',
	'Delete account': '删除账号',
	'Delete my account': '删除我的账号',
	'Deleting…': '删除中…',
	'Display name': '显示名称',
	'Draw': '平局',
	'Email': '邮箱',
	'English': 'English',
	'Enter and confirm your new password.': '请输入并确认你的新密码。',
	'Enter the email you signed up with and we will send a reset link.': '输入注册邮箱，我们会发送重置链接。',
	'Error': '错误',
	'FIFA ranking': 'FIFA 排名',
	'Failed': '失败',
	'Find a match, team or league.': '查找比赛、球队或联赛。',
	'Forgot password?': '忘记密码？',
	'Golden Boot': '金靴',
	'Golden Boot pick': '金靴预测',
	'Golden Boot pick and current top-scorer table.': '金靴预测和当前射手榜。',
	'Goals': '进球',
	'Got it': '知道了',
	'Group': '小组',
	'Group tables': '小组积分榜',
	'Groups': '小组',
	'Hide friends’ tips': '隐藏好友预测',
	'Hit rate': '命中率',
	'Home': '首页',
	'How everyone tipped': '大家的预测',
	'If the email is registered, a link is on the way.': '如果该邮箱已注册，重置链接将发送到邮箱。',
	'Image must be 5 MB or smaller.': '图片大小不能超过 5 MB。',
	'Install': '安装',
	'Install VM Tipping': '安装 VM Tipping',
	'Join the World Cup tipping competition.': '加入世界杯预测比赛。',
	'Jump to current round': '跳到当前轮次',
	'Knockout': '淘汰赛',
	'Knockout bracket': '淘汰赛赛程图',
	'Lagret': '已保存',
	'Leagues': '联赛',
	'Light theme': '浅色主题',
	'Live': '直播中',
	'Live API search unavailable': '实时 API 搜索不可用',
	'Load failed': '加载失败',
	'Loading search…': '正在加载搜索…',
	'Loading matches…': '正在加载比赛…',
	'Loading…': '加载中…',
	'Lock': '锁定',
	'Locked.': '已锁定。',
	'Locks': '锁定时间',
	'Locks at kickoff.': '开球时锁定。',
	'Log in': '登录',
	'Log out': '退出登录',
	'Match tips': '比赛预测',
	'Match Tips': '比赛预测',
	'Matches': '比赛',
	'Matches you haven’t tipped': '尚未预测的比赛',
	'Missing': '未填写',
	'New here?': '新用户？',
	'New password': '新密码',
	'No Golden Boot pick.': '暂无金靴预测。',
	'No best-third picks.': '暂无最佳小组第三预测。',
	'No candidates yet.': '暂无候选人。',
	'No goals registered yet.': '尚无进球记录。',
	'No leagues': '暂无联赛',
	'No local candidates matched, and live API search is unavailable.': '本地没有匹配候选人，实时 API 搜索不可用。',
	'No matching World Cup candidates found.': '没有找到匹配的世界杯候选人。',
	'No missing match tips': '没有遗漏的比赛预测',
	'No one else has picked this match.': '还没有其他人预测这场比赛。',
	'No one in this league has picked this match.': '这个联赛中还没有人预测这场比赛。',
	'No results.': '没有结果。',
	'No scored matches yet.': '暂无已计分比赛。',
	'Not allowed': '无权访问',
	'Not synced yet': '尚未同步',
	'Notifications': '通知',
	'OR': '或',
	'Open leagues': '打开联赛',
	'Password': '密码',
	'Password must be at least 8 characters.': '密码至少需要 8 个字符。',
	'Password updated — sending you to sign in…': '密码已更新，即将跳转到登录页…',
	'Penalties': '点球',
	'Pick': '选择',
	'Picked': '已预测',
	'Player': '球员',
	'Player card': '玩家卡片',
	'PNG or JPG, up to 5 MB.': 'PNG 或 JPG，最大 5 MB。',
	'Pre-kickoff reminder': '开球前提醒',
	'Predicted champion': '预测冠军',
	'Predicted winner': '预测冠军',
	'Pts': '分',
	'Push': '推送',
	'Read-only - a friend\'s World Cup tips.': '只读 - 好友的世界杯预测。',
	'Reset link sent - check your inbox.': '重置链接已发送，请检查收件箱。',
	'Reset password': '重置密码',
	'Result': '赛果',
	'Round': '轮次',
	'Save': '保存',
	'Save changes': '保存更改',
	'Save failed': '保存失败',
	'Saved': '已保存',
	'Saved · changes are saved automatically': '已保存 · 更改会自动保存',
	'Saving…': '保存中…',
	'Scored tips': '已计分预测',
	'Search': '搜索',
	'Search by player name…': '按球员姓名搜索…',
	'Search for a Golden Boot player': '搜索金靴球员',
	'Search in VM Tipping': '搜索 VM Tipping',
	'Search match, team, group or league': '搜索比赛、球队、小组或联赛',
	'Search more players': '搜索更多球员',
	'Searching…': '搜索中…',
	'See match tips': '查看比赛预测',
	'Send link': '发送链接',
	'Send reset link': '发送重置链接',
	'Send test notification': '发送测试通知',
	'Sending…': '发送中…',
	'Sent': '已发送',
	'Settings': '设置',
	'Shortlist': '候选名单',
	'Show %': '显示 %',
	'Show friends’ tips': '显示好友预测',
	'Show odds': '显示赔率',
	'Show the welcome card again': '重新显示欢迎卡片',
	'Sign in': '登录',
	'Simplified Chinese': '简体中文',
	'Standard theme': '标准主题',
	'Submit before kickoff.': '开球前提交预测。',
	'Team': '球队',
	'Teams': '球队',
	'The card is active and will stay on the home page until you close it.': '欢迎卡片已启用，会显示在首页，直到你关闭它。',
	'The card is hidden for this user on this device.': '欢迎卡片已在此设备上对该用户隐藏。',
	'The link is invalid or expired.': '链接无效或已过期。',
	'The official Golden Boot standings.': '官方金靴榜。',
	'The passwords do not match.': '两次输入的密码不一致。',
	'The tournament has started - the World Cup tip is final.': '赛事已开始 - 世界杯预测已锁定。',
	'Today': '今天',
	'Top scorers': '射手榜',
	'Top-scorer pick': '金靴预测',
	'Tournament': '赛事',
	'Try another tab.': '试试其他标签。',
	'Type to search...': '输入关键词搜索…',
	'Update password': '更新密码',
	'Updated': '更新于',
	'View all matches': '查看全部比赛',
	'Welcome card': '欢迎卡片',
	'Welcome to VM Tipping': '欢迎使用 VM Tipping',
	'Where the tournament is now': '赛事当前进度',
	'Where we are now': '当前进度',
	'Whole tournament': '整届赛事',
	'World Cup Tips': '世界杯预测',
	'World Cup theme': '世界杯主题',
	'World Cup tips': '世界杯预测',
	'World Cup tips in one league.': '一个联赛里完成世界杯预测。',
	'Wrong email or password.': '邮箱或密码错误。',
	'You tipped': '你的预测',
	'Your Golden Boot pick': '你的金靴预测',
	'Your tip': '你的预测',
	'actual': '实际',
	'advances': '晋级',
	'aet': '加时后',
	'gap': '偏差',
	'helt rette': '完全命中',
	'locked': '已锁定',
	'missing': '未填写',
	'now': '现在',
	'on TV': '电视转播',
	'pens': '点球',
	'same score as the final result': '比分完全命中',
	'through': '晋级',
	'to simulate the tournament.': '来模拟赛事。',
	'top-scorer pick': '金靴预测',
	'vs': 'vs',
	'you': '你'
};

export function translateChinese(text: string): string {
	return zh[text] ?? text;
}
